services:
  # Servicio 1: La Base de Datos
  db:
    image: postgres:14.22
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: btp_psswd00
      POSTGRES_DB: approval_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
      build: .
      ports:
        - "3000:3000"
      environment:
        # IMPORTANTE: Aquí usamos 'db' en lugar de 'localhost' porque 
        # dentro de la red de Docker se llaman por su nombre de servicio.
        - DATABASE_URL=postgresql://sa:btp_psswd00@db:5432/approval_db
      depends_on:
        - db

volumes:
  pgdata: